version: '3'
services:
  indonesia-api:
    image: 'node:18.15-alpine'
    container_name: indonesia-api
    working_dir: /app
    restart: unless-stopped
    env_file: .env
    volumes:
      - './:/app'
    command: >
      sh -c "echo \"update-notifier=false\" > .npmrc && \
      npm start"
