version: '3'
services:
  indonesia-api:
    image: indonesia-api
    expose:
      - 3001
    ports:
      - 3001:${PORT}
    container_name: indonesia-api
    working_dir: /app
    restart: unless-stopped
    env_file: .env
    volumes:
      - './:/app'
    command: >
      sh -c "echo \"update-notifier=false\" > .npmrc && \
      npm start"
