/**
 * @module #config/args
 *
 * @typedef {import('./defaults.mjs').BasicAuth} BasicAuth
 */

/**
 * Constants
 *
 * @typedef {Object} Args
 * @property {string} XLSX_DIRECTORY
 * @property {string} SOURCE_DIRECTORY
 * @property {string} TARGET_DIRECTORY
 * @property {string} DATA_MODEL_FILE_NAME
 * @property {string} SWAGGER_YAML_FILE_PATH
 * @property {string} SWAGGER_JSON_FILE_PATH
 * @property {string} IMPACT_OVERALL_DATASET_NAME
 * @property {string} WUR_PORTAL_DATASET_NAME
 * @property {string} WUR_CITATIONS_DATASET_NAME
 * @property {string} WUR_METRICS_DATASET_NAME
 * @property {string} WUR_ID_MAPPING_DATASET_NAME
 * @property {string} WUR_REF_DATA_DATASET_NAME
 * @property {string} IMPACT_OVERALL_COMPONENT_SCHEMA
 * @property {string} WUR_PORTAL_COMPONENT_SCHEMA
 * @property {string} WUR_CITATIONS_COMPONENT_SCHEMA
 * @property {string} WUR_METRICS_COMPONENT_SCHEMA
 * @property {string} WUR_ID_MAPPING_COMPONENT_SCHEMA
 * @property {string} WUR_REF_DATA_COMPONENT_SCHEMA
 * @property {string} IMPACT_OVERALL_LABEL
 * @property {string} WUR_PORTAL_LABEL
 * @property {string} WUR_CITATIONS_LABEL
 * @property {string} WUR_METRICS_LABEL
 * @property {string} WUR_ID_MAPPING_LABEL
 * @property {string} WUR_REF_DATA_LABEL
 * @property {string} IMPACT_OVERALL_FILE_NAME
 * @property {string} WUR_PORTAL_FILE_NAME
 * @property {string} WUR_CITATIONS_FILE_NAME
 * @property {string} WUR_METRICS_FILE_NAME
 * @property {string} WUR_ID_MAPPING_FILE_NAME
 * @property {string} WUR_REF_DATA_FILE_NAME
 * @property {number} SCHEMA_MIN_YEAR
 * @property {number} SCHEMA_MAX_YEAR
 * @property {BasicAuth} BASIC_AUTH_USERS
 * @property {number} PORT
 */

import 'dotenv/config'
import nconf from 'nconf'

import {
  DEFAULT_XLSX_DIRECTORY,
  DEFAULT_SOURCE_DIRECTORY,
  DEFAULT_TARGET_DIRECTORY,
  DEFAULT_DATA_MODEL_FILE_NAME,
  DEFAULT_SWAGGER_YAML_FILE_PATH,
  DEFAULT_SWAGGER_JSON_FILE_PATH,
  DEFAULT_IMPACT_OVERALL_DATASET_NAME,
  DEFAULT_WUR_PORTAL_DATASET_NAME,
  DEFAULT_WUR_CITATIONS_DATASET_NAME,
  DEFAULT_WUR_METRICS_DATASET_NAME,
  DEFAULT_WUR_ID_MAPPING_DATASET_NAME,
  DEFAULT_WUR_REF_DATA_DATASET_NAME,
  DEFAULT_IMPACT_OVERALL_COMPONENT_SCHEMA,
  DEFAULT_WUR_PORTAL_COMPONENT_SCHEMA,
  DEFAULT_WUR_CITATIONS_COMPONENT_SCHEMA,
  DEFAULT_WUR_METRICS_COMPONENT_SCHEMA,
  DEFAULT_WUR_ID_MAPPING_COMPONENT_SCHEMA,
  DEFAULT_WUR_REF_DATA_COMPONENT_SCHEMA,
  DEFAULT_IMPACT_OVERALL_LABEL,
  DEFAULT_WUR_PORTAL_LABEL,
  DEFAULT_WUR_CITATIONS_LABEL,
  DEFAULT_WUR_METRICS_LABEL,
  DEFAULT_WUR_ID_MAPPING_LABEL,
  DEFAULT_WUR_REF_DATA_LABEL,
  DEFAULT_IMPACT_OVERALL_FILE_NAME,
  DEFAULT_WUR_PORTAL_FILE_NAME,
  DEFAULT_WUR_CITATIONS_FILE_NAME,
  DEFAULT_WUR_METRICS_FILE_NAME,
  DEFAULT_WUR_ID_MAPPING_FILE_NAME,
  DEFAULT_WUR_REF_DATA_FILE_NAME,
  DEFAULT_SCHEMA_MIN_YEAR,
  DEFAULT_SCHEMA_MAX_YEAR,
  DEFAULT_PORT
} from './defaults.mjs'

export * from './defaults.mjs'

function transform ({ key, value }) {
  if (key === 'BASIC_AUTH_USERS') {
    return {
      key,
      value: JSON.parse(value)
    }
  }

  if (
    key === 'PORT' ||
    key === 'SCHEMA_MIN_YEAR' ||
    key === 'SCHEMA_MAX_YEAR') {
    return {
      key,
      value: Number(value)
    }
  }

  return {
    key,
    value
  }
}

/**
 * @type {Args}
 */
export const args = nconf.argv({ transform }).env({ transform }).defaults({
  XLSX_DIRECTORY: DEFAULT_XLSX_DIRECTORY,
  SOURCE_DIRECTORY: DEFAULT_SOURCE_DIRECTORY,
  TARGET_DIRECTORY: DEFAULT_TARGET_DIRECTORY,

  DATA_MODEL_FILE_NAME: DEFAULT_DATA_MODEL_FILE_NAME,
  SWAGGER_YAML_FILE_PATH: DEFAULT_SWAGGER_YAML_FILE_PATH,
  SWAGGER_JSON_FILE_PATH: DEFAULT_SWAGGER_JSON_FILE_PATH,

  IMPACT_OVERALL_DATASET_NAME: DEFAULT_IMPACT_OVERALL_DATASET_NAME,
  WUR_PORTAL_DATASET_NAME: DEFAULT_WUR_PORTAL_DATASET_NAME,
  WUR_CITATIONS_DATASET_NAME: DEFAULT_WUR_CITATIONS_DATASET_NAME,
  WUR_METRICS_DATASET_NAME: DEFAULT_WUR_METRICS_DATASET_NAME,
  WUR_ID_MAPPING_DATASET_NAME: DEFAULT_WUR_ID_MAPPING_DATASET_NAME,
  WUR_REF_DATA_DATASET_NAME: DEFAULT_WUR_REF_DATA_DATASET_NAME,

  IMPACT_OVERALL_COMPONENT_SCHEMA: DEFAULT_IMPACT_OVERALL_COMPONENT_SCHEMA,
  WUR_PORTAL_COMPONENT_SCHEMA: DEFAULT_WUR_PORTAL_COMPONENT_SCHEMA,
  WUR_CITATIONS_COMPONENT_SCHEMA: DEFAULT_WUR_CITATIONS_COMPONENT_SCHEMA,
  WUR_METRICS_COMPONENT_SCHEMA: DEFAULT_WUR_METRICS_COMPONENT_SCHEMA,
  WUR_ID_MAPPING_COMPONENT_SCHEMA: DEFAULT_WUR_ID_MAPPING_COMPONENT_SCHEMA,
  WUR_REF_DATA_COMPONENT_SCHEMA: DEFAULT_WUR_REF_DATA_COMPONENT_SCHEMA,

  IMPACT_OVERALL_LABEL: DEFAULT_IMPACT_OVERALL_LABEL,
  WUR_PORTAL_LABEL: DEFAULT_WUR_PORTAL_LABEL,
  WUR_CITATIONS_LABEL: DEFAULT_WUR_CITATIONS_LABEL,
  WUR_METRICS_LABEL: DEFAULT_WUR_METRICS_LABEL,
  WUR_ID_MAPPING_LABEL: DEFAULT_WUR_ID_MAPPING_LABEL,
  WUR_REF_DATA_LABEL: DEFAULT_WUR_REF_DATA_LABEL,

  IMPACT_OVERALL_FILE_NAME: DEFAULT_IMPACT_OVERALL_FILE_NAME,
  WUR_PORTAL_FILE_NAME: DEFAULT_WUR_PORTAL_FILE_NAME,
  WUR_CITATIONS_FILE_NAME: DEFAULT_WUR_CITATIONS_FILE_NAME,
  WUR_METRICS_FILE_NAME: DEFAULT_WUR_METRICS_FILE_NAME,
  WUR_ID_MAPPING_FILE_NAME: DEFAULT_WUR_ID_MAPPING_FILE_NAME,
  WUR_REF_DATA_FILE_NAME: DEFAULT_WUR_REF_DATA_FILE_NAME,

  SCHEMA_MIN_YEAR: DEFAULT_SCHEMA_MIN_YEAR,
  SCHEMA_MAX_YEAR: DEFAULT_SCHEMA_MAX_YEAR,

  BASIC_AUTH_USERS: {},
  PORT: DEFAULT_PORT
}).get()

export default new Map(Object.entries(args))
